// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHdcP0EJWsay9SCMLheoiFEWMVx5fIkrE',
    appId: '1:843931067903:web:207a07377983ad75c6b3ca',
    messagingSenderId: '843931067903',
    projectId: 'empbuddy-c2ca2',
    authDomain: 'empbuddy-c2ca2.firebaseapp.com',
    storageBucket: 'empbuddy-c2ca2.appspot.com',
    measurementId: 'G-N2V402SCWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw4JTfemPkrDc0ddzwexDF6dKNZv6hyDk',
    appId: '1:843931067903:android:29cd863074f6bebdc6b3ca',
    messagingSenderId: '843931067903',
    projectId: 'empbuddy-c2ca2',
    storageBucket: 'empbuddy-c2ca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUus7R-SE7Hps2Sb0tKXdCPjkoO0kRRe8',
    appId: '1:843931067903:ios:f8ce59b827877023c6b3ca',
    messagingSenderId: '843931067903',
    projectId: 'empbuddy-c2ca2',
    storageBucket: 'empbuddy-c2ca2.appspot.com',
    iosBundleId: 'com.example.empBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUus7R-SE7Hps2Sb0tKXdCPjkoO0kRRe8',
    appId: '1:843931067903:ios:5ab9bc6193a5bcadc6b3ca',
    messagingSenderId: '843931067903',
    projectId: 'empbuddy-c2ca2',
    storageBucket: 'empbuddy-c2ca2.appspot.com',
    iosBundleId: 'com.example.empBuddy.RunnerTests',
  );
}
